version: "3"

services:
  appgo:
    container_name: appbank
    entrypoint: ./.docker/entrypoint.sh
    build: .
    ports:
      - "50052:50052"
    volumes:
      - .:/go/src/
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    networks:
      - kafka_go_store
      - postgres_codebank

#  db:
#    image: postgres:9.4
#    restart: always
#    tty: true
#    volumes:
#      - .pgdata:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=codebank
#    ports:
#      - "5432:5432"
#    extra_hosts:
#      - "host.docker.internal:172.17.0.1"
#    networks:
#      - kafka_go_store

#  pgadmin:
#    image: dpage/pgadmin4
#    tty: true
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@user.com
#      - PGADMIN_DEFAULT_PASSWORD=123456
#    ports:
#      - "9000:80"
#    depends_on:
#      - db
#    extra_hosts:
#      - "host.docker.internal:172.17.0.1"

networks:
  postgres_codebank:
    external: true
  kafka_go_store:
    external: true
