version: '3'

services:
  appapi:
    build: .
    entrypoint: dockerize -wait tcp://db:5433 -timeout 40s ./.docker/entrypoint.sh
    container_name: imersao-fullcycle-store-api-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - db
    extra_hosts:
      - 'host.docker.internal:172.17.0.1'
    networks:
      - kafka_go_store

  db:
    build: .docker/postgres
    container_name: imersao-fullcycle-store-api-db
    restart: always
    tty: true
    volumes:
      - .docker/postgres/pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=store
      - PGPORT=5433
    networks:
      - kafka_go_store

networks:
  kafka_go_store:
    external: true


