import type { NextPage } from 'next'
import Head from 'next/head'
import { Typography } from "@material-ui/core";

const Page404: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Page Not Found</title>
                {/*<meta name="description" content="Generated by create next app" />*/}
                {/*<link rel="icon" href="/favicon.ico" />*/}
            </Head>

            <Typography component="h1" variant="h4" color="textPrimary" align="center" gutterBottom>
                404 - Page Not Found
            </Typography>
        </div>
    )
}

export default Page404;

